# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.6
    - 2.7
    - 3.0
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - python -m unittest discover

